// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["Nsend", "pi/m/Source", "Cmon"], function(aPi, mSource, Cmon) {
  var ConvList;
  return ConvList = (function(superClass) {
    extend(ConvList, superClass);

    function ConvList() {
      return ConvList.__super__.constructor.apply(this, arguments);
    }

    ConvList.prototype.attr = function() {
      return ConvList.__super__.attr.apply(this, arguments).concat(["view"]);
    };

    ConvList.prototype.draw = function(List) {
      var convId, i, len, tmpl;
      tmpl = this.rt.source(this.a.view);
      this.clear();
      for (i = 0, len = List.length; i < len; i++) {
        convId = List[i];
        this.e.append(tmpl({
          id: convId
        }));
      }
      return this.rt.pi(this.e);
    };

    ConvList.prototype.query = function() {
      return this.nsend(["user/conv_list", Cmon.user_id()], (function(_this) {
        return function(status, List) {
          return _this.draw(List);
        };
      })(this));
    };

    ConvList.prototype.autojoin = function(List) {
      var convId, i, len, seen, storedConvId;
      storedConvId = Cmon.conv_id();
      seen = 0;
      for (i = 0, len = List.length; i < len; i++) {
        convId = List[i];
        if (storedConvId === convId) {
          this.rpc("#bullet@pub_event", ["conv/status/join", convId]);
          seen = 1;
        }
      }
      if (!seen) {
        return this.rpc("#bullet@pub_event", ["conv/status/part"]);
      }
    };

    ConvList.prototype.init = function() {
      this.sub("#bullet@conv/status/join", (function(_this) {
        return function(ev, args) {
          return _this.query();
        };
      })(this));
      this.sub("#bullet@conv/status/part", (function(_this) {
        return function(ev, args) {
          return _this.query();
        };
      })(this));
      this.sub("#bullet@user/status/registered", (function(_this) {
        return function(ev, args) {
          return _this.query();
        };
      })(this));
      this.sub("#bullet@user/status/anonymous", (function(_this) {
        return function(ev, args) {
          return _this.query();
        };
      })(this));
      this.sub("#bullet@user/status/not_logged", (function(_this) {
        return function(ev, args) {
          return _this.clear();
        };
      })(this));
      return this.wait_ajax_done((function(_this) {
        return function() {
          return _this.nsend(["user/conv_list", Cmon.user_id()], function(status, List) {
            return _this.autojoin(List);
          });
        };
      })(this));
    };

    return ConvList;

  })(aPi);
});
