// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["pi/Pi", "pi/m/Source"], function(aPi, mSource) {
  var ConvList;
  return ConvList = (function(superClass) {
    extend(ConvList, superClass);

    function ConvList() {
      return ConvList.__super__.constructor.apply(this, arguments);
    }

    ConvList.prototype.attr = function() {
      return ConvList.__super__.attr.apply(this, arguments).concat(["view"]);
    };

    ConvList.prototype.init = function() {
      this.sub("#bullet@conv/users", (function(_this) {
        return function(ev, args) {
          var List, email, i, id, len, name, ref, status, tmpl;
          _this.debug("USERS", args);
          _this.empty();
          status = args[0], List = args[1];
          tmpl = _this.rt.source(_this.a.view);
          for (i = 0, len = List.length; i < len; i++) {
            ref = List[i], id = ref[0], name = ref[1], email = ref[2];
            _this.e.append(tmpl({
              id: id,
              display: _this.displayName(id, name, email)
            }));
          }
          return _this.rt.pi(_this.e);
        };
      })(this));
      this.sub("#bullet@conv/status/join", (function(_this) {
        return function(ev, args) {
          return _this.rpc("#bullet@query_conv_users");
        };
      })(this));
      return this.sub("#bullet@conv/status/part", (function(_this) {
        return function(ev, args) {
          return _this.rpc("#bullet@query_conv_users");
        };
      })(this));
    };

    ConvList.prototype.displayName = function(id, name, email) {
      if (name !== "undefined") {
        return name;
      } else if (email !== "undefined") {
        return email;
      } else {
        return id;
      }
    };

    return ConvList;

  })(aPi);
});
