// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["pi/Pi"], function(Pi) {
  var Dumper;
  return Dumper = (function(superClass) {
    extend(Dumper, superClass);

    function Dumper() {
      return Dumper.__super__.constructor.apply(this, arguments);
    }

    Dumper.prototype.attr = function() {
      return Dumper.__super__.attr.apply(this, arguments).concat(["stamp", "text"]);
    };

    Dumper.prototype.init = function() {
      return this.sub("#bullet@new_msg", (function(_this) {
        return function(e, args) {
          var convId, display, email, holder, id, name, ref, ref1, stamp, stamp_div, text, text_div;
          convId = args[0], (ref = args[1], id = ref[0], name = ref[1], email = ref[2]), (ref1 = args[2], stamp = ref1[0], text = ref1[1]);
          display = name ? name : email ? email : id;
          text_div = $("<div>").addClass(_this.a.text).html(text);
          stamp_div = $("<div>").addClass(_this.a.stamp).html(stamp + "&nbsp;&nbsp;" + display + ":");
          holder = $("<div>").addClass("row");
          holder.prepend(text_div);
          holder.prepend(stamp_div);
          return _this.e.prepend(holder);
        };
      })(this));
    };

    return Dumper;

  })(Pi);
});
