// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["pi/Pi"], function(Pi) {
  var Dumper;
  return Dumper = (function(superClass) {
    extend(Dumper, superClass);

    function Dumper() {
      return Dumper.__super__.constructor.apply(this, arguments);
    }

    Dumper.prototype.attr = function() {
      return Dumper.__super__.attr.apply(this, arguments).concat(["row"]);
    };

    Dumper.prototype.init = function() {
      return this.sub("#bullet@stub", (function(_this) {
        return function(e, args) {
          var response, row;
          response = args[0];
          row = $("<div>").addClass(_this.a.row);
          row.html(response);
          return _this.e.append(row);
        };
      })(this));
    };

    return Dumper;

  })(Pi);
});
