// Generated by CoffeeScript 1.9.3
require(["conf/requirejs"], function(Conf) {
  require.config(Conf);
  return require(["pi/router"], function(Router) {
    var router;
    return router = new Router;
  });
});
