// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["Nsend", "Cmon"], function(Pi, Cmon) {
  var Online;
  return Online = (function(superClass) {
    extend(Online, superClass);

    function Online() {
      return Online.__super__.constructor.apply(this, arguments);
    }

    Online.prototype.attr = function() {
      return Online.__super__.attr.apply(this, arguments).concat(["view"]);
    };

    Online.prototype.init = function() {
      return this.wait_ajax_done((function(_this) {
        return function() {
          return _this.query();
        };
      })(this));
    };

    Online.prototype.draw = function(userList) {
      var i, len, tmpl, userInfo;
      this.clear();
      tmpl = this.rt.source(this.a.view);
      for (i = 0, len = userList.length; i < len; i++) {
        userInfo = userList[i];
        this.e.append(tmpl({
          id: userInfo[0],
          display: Cmon.displayNameA(userInfo)
        }));
      }
      return this.rt.pi(this.e);
    };

    Online.prototype.query = function() {
      return this.nsend(["user/online", Cmon.sid()], (function(_this) {
        return function(status, userList) {
          _this.debug(status, userList);
          return _this.draw(userList);
        };
      })(this));
    };

    return Online;

  })(Pi);
});
