// Generated by CoffeeScript 1.9.3
define([], function() {
  var Util;
  return Util = (function() {
    function Util() {}

    Util.prototype.list2hash = function(list) {
      var elem, i, len, ret;
      ret = {};
      for (i = 0, len = list.length; i < len; i++) {
        elem = list[i];
        ret[elem.name] = elem.value;
      }
      return ret;
    };

    return Util;

  })();
});
