// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["Nsend"], function(Pi) {
  var ConnStatus;
  return ConnStatus = (function(superClass) {
    extend(ConnStatus, superClass);

    function ConnStatus() {
      return ConnStatus.__super__.constructor.apply(this, arguments);
    }

    ConnStatus.prototype.init = function() {
      ConnStatus.__super__.init.apply(this, arguments);
      this.bsub("conn/open", (function(_this) {
        return function() {
          return _this.e.css({
            color: "#fff"
          });
        };
      })(this));
      return this.bsub("conn/close", (function(_this) {
        return function() {
          return _this.e.css({
            color: "#aaa"
          });
        };
      })(this));
    };

    return ConnStatus;

  })(Pi);
});
