// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["Nsend"], function(aPi) {
  var LoginFacebook;
  return LoginFacebook = (function(superClass) {
    extend(LoginFacebook, superClass);

    function LoginFacebook() {
      return LoginFacebook.__super__.constructor.apply(this, arguments);
    }

    LoginFacebook.prototype.init = function() {
      return this.wait_ajax_done((function(_this) {
        return function() {
          return _this.ncall(function(bo) {
            return _this.e.css({
              display: "inline-block",
              "white-space": "nowrap"
            });
          });
        };
      })(this));
    };

    return LoginFacebook;

  })(aPi);
});
