// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["Nsend", "pi/m/Source", "Cmon"], function(aPi, mSource, Cmon) {
  var LoginStatus;
  return LoginStatus = (function(superClass) {
    extend(LoginStatus, superClass);

    function LoginStatus() {
      return LoginStatus.__super__.constructor.apply(this, arguments);
    }

    LoginStatus.prototype.attr = function() {
      return LoginStatus.__super__.attr.apply(this, arguments).concat(["login", "logout"]);
    };

    LoginStatus.prototype.logged = function(user) {
      var tmpl;
      this.clear();
      console.log("XXX", user);
      tmpl = mSource.get(this.a.logout);
      this.e.html(tmpl({
        display: Cmon.displayNameA(user)
      }));
      return this.rt.pi(this.e);
    };

    LoginStatus.prototype.not_logged = function() {
      this.e.html(mSource.get(this.a.login));
      return this.rt.pi(this.e);
    };

    LoginStatus.prototype.init = function() {
      this.sub("#bullet@user/status/registered", (function(_this) {
        return function(ev, user) {
          return _this.logged(user);
        };
      })(this));
      this.sub("#bullet@user/status/not_logged", (function(_this) {
        return function(ev) {
          return _this.not_logged();
        };
      })(this));
      return this.sub("#bullet@user/status/anonymous", (function(_this) {
        return function(ev, user) {
          return _this.logged(user);
        };
      })(this));
    };

    return LoginStatus;

  })(aPi);
});
