// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["pi/Pi", "pi/m/Source"], function(aPi, mSource) {
  var LoginStatus;
  return LoginStatus = (function(superClass) {
    extend(LoginStatus, superClass);

    function LoginStatus() {
      return LoginStatus.__super__.constructor.apply(this, arguments);
    }

    LoginStatus.prototype.attr = function() {
      return LoginStatus.__super__.attr.apply(this, arguments).concat(["login", "logout"]);
    };

    LoginStatus.prototype.init = function() {
      this.sub("#bullet@registered", (function(_this) {
        return function(ev, args) {
          var displayName, email, name, ref, status, tmpl, userId;
          status = args[0], (ref = args[1], userId = ref[0], name = ref[1], email = ref[2]);
          displayName = name ? name : email;
          tmpl = mSource.get(_this.a.logout);
          _this.e.html(tmpl({
            display: displayName
          }));
          return _this.rt.pi(_this.e);
        };
      })(this));
      return this.sub("#bullet@user/logout", (function(_this) {
        return function(ev) {
          _this.e.html(mSource.get(_this.a.login));
          return _this.rt.pi(_this.e);
        };
      })(this));
    };

    return LoginStatus;

  })(aPi);
});
